require('./osc~phasor~-tests.js')
require('./noise~-tests.js')
require('./line~-tests.js')
require('./sig~-tests.js')
require('./tabread~-tests.js')
require('./lop~hip~bp~vcf~-tests.js')
require('./+~-~*~-tests.js')
require('./delwrite~delread~-tests.js')